workspace = { members = ["another_function", "debug_print"] }
[package]
name = "commom_programing_concenps"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
